Expand release checks

diff --git a/build/release b/build/release
--- a/build/release
+++ b/build/release
@@ -14,6 +14,13 @@ then
     exit 1
 fi
 
+version="$(echo $1 | sed -e 's/^v//')"
+if ! grep -E "^v?${version}\\s*[0-9]{4}-[0-9]{2}-[0-9]{2}" CHANGES
+then
+    echo "ERROR: Version not in CHANGES"
+    exit 1
+fi
+
 set -x
 build/patch-version $1
 perl Makefile.PL
