Extend release checks

diff --git a/build/release b/build/release
--- a/build/release
+++ b/build/release
@@ -8,6 +8,12 @@ then
     exit 1
 fi
 
+if [ -n "$(git tag --list "$1")" ]
+then
+    echo "ERROR: Tag $1 exists"
+    exit 1
+fi
+
 set -x
 build/patch-version $1
 perl Makefile.PL
